@host = http://localhost
@port = 5001
@Restaurants.API_HostAddress = {{host}}:{{port}}
@token = CfDJ8Mf_gNlt6O1HmcLMoKQa213z9yqWjihHchW36gz22LtY-NSkxRZkmpA69J0LGO-ue1sGnDFdCsxYX7OtsKrL3OcLgW6_qjuKlA6VZqVHT_jh5wgnCrH95y6j7BVdRJejcFq3URQSjZxb--EwSE91rpCSCIqphgnWVbWf90I0XoavAlLoyAW5kOkWKDqLbpwf8gSxk18GtJmlKicJq0vEaL9ZUm4eqXoyplncKGi5a0mQgQ0ihQAq0psv4FpNyTR82nHETPcfgDh8qSqTgMjHvUpben6BmDzzNBoKV_z60F-FAzM5lGPxZ8o7dS8iBiH_V71eNk5wl93ivVATq7Eamx5IY2tbdum2SRQKNVVMhr2ht3vCc_uDLl2Lj9lnenRp-Wb6F9htkaTyLSYHTe5TBmbKgcQdfwd52KyjRMGYVKBY3Im06Vp_RbKB1mWE8R9D-Kdy_FhUCP32Mm1Q-F_y71--V-r2TPVBZonqvbhwomA5Ui4Y_r7k2ucbnOjuhhserTNC_O0Z7GotPAtv_QLeMZf7X5XvdhR4n2TirC1ef0In-Q4aoNSF73Xk_pVbP20Q6TuPGexNPThhXI3hlSvOq1arGegcBaHQZTolhRTUs5jLuDlNJx7pCQ5l8xFyFGlk9BALINb_IVBcbKmujwg8s45UdRhYqezMMdHfcynRtH8silp7HWyitW1FZRzJa6UUULjH0NJ7x_kh4NTwOMSsVRc


GET {{Restaurants.API_HostAddress}}/api/Restaurants
Authorization: Bearer {{token}}

###
GET {{Restaurants.API_HostAddress}}/api/Restaurants?searchPhrase=Wendy
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/Restaurants/4

###

POST {{Restaurants.API_HostAddress}}/api/Restaurants
Content-Type: application/json

{
  "Name": "Tasty Test",
  "Description": "Tasty Test is a fast food restaurant",
  "Category": "American",
  "HasDelivery": true,
  "ContactEmail": "j8yQh@example.com",
  "ContactNumber": "1234567890",
  "City": "Startholme",
  "Street": "Main Street",
  "PostalCode": "111111"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/Restaurants/7

###

PATCH {{Restaurants.API_HostAddress}}/api/Restaurants/4
Content-Type: application/json

{
  "Name": "Changes made",
  "Description": "Changes made",
  "HasDelivery": true
}

###
POST {{Restaurants.API_HostAddress}}/api/restaurants/4/dishes
Content-Type: application/json

{
  "name": "Big Mac",
  "description": "Two all-beef patties, special sauce, lettuce, cheese, pickles, onions on a sesame seed bun.",
  "price": 12.7,
  "kiloCalories": 500
}

###
GET {{Restaurants.API_HostAddress}}/api/restaurants/4/dishes
Content-Type: application/json

###
GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes/1
Content-Type: application/json

###
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes/1
Content-Type: application/json

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "testuser1@example.com",
  "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "testuser1@example.com",
  "password": "Password1!"
}