@host = http://localhost
@port = 5001
@Restaurants.API_HostAddress = {{host}}:{{port}}



GET {{Restaurants.API_HostAddress}}/api/Restaurants

###

GET {{Restaurants.API_HostAddress}}/api/Restaurants/4

###

POST {{Restaurants.API_HostAddress}}/api/Restaurants
Content-Type: application/json

{
  "Name": "Tasty Test",
  "Description": "Tasty Test is a fast food restaurant",
  "Category": "American",
  "HasDelivery": true,
  "ContactEmail": "j8yQh@example.com",
  "ContactNumber": "1234567890",
  "City": "Startholme",
  "Street": "Main Street",
  "PostalCode": "111111"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/Restaurants/7

###

PATCH {{Restaurants.API_HostAddress}}/api/Restaurants/4
Content-Type: application/json

{
  "Name": "Changes made",
  "Description": "Changes made",
  "HasDelivery": true
}

###
POST {{Restaurants.API_HostAddress}}/api/restaurants/4/dishes
Content-Type: application/json

{
  "name": "Big Mac",
  "description": "Two all-beef patties, special sauce, lettuce, cheese, pickles, onions on a sesame seed bun.",
  "price": 12.7,
  "kiloCalories": 500
}

###
GET {{Restaurants.API_HostAddress}}/api/restaurants/4/dishes
Content-Type: application/json

###
GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes/1
Content-Type: application/json

###
DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes/1
Content-Type: application/json

###

POST {{Restaurants.API_HostAddress}}/register
Content-Type: application/json

{
  "email": "testuser1@example.com",
  "password": "111111"
}

###

POST {{Restaurants.API_HostAddress}}/login
Content-Type: application/json

{
  "email": "testuser1@example.com",
  "password": "111111"
}